/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class BusinessUserRole   {
    public static const ADMIN:int = 1;
    public static const NORMAL:int = 2;

    public static const VALID_VALUES:Set = new Set(ADMIN, NORMAL);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[ADMIN] = "ADMIN";
      VALUES_TO_NAMES[NORMAL] = "NORMAL";

    }
  }
}
