/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type {

import org.apache.thrift.Set;
import org.apache.thrift.type.BigInteger;
import flash.utils.ByteArray;
import flash.utils.Dictionary;

  public class Constants {

    public static const EDAM_NOTE_SOURCE_WEB_CLIP:String = "web.clip";

    public static const EDAM_NOTE_SOURCE_MAIL_CLIP:String = "mail.clip";

    public static const EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY:String = "mail.smtp";

  }
}
