/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class PrivilegeLevel   {
    public static const NORMAL:int = 1;
    public static const PREMIUM:int = 3;
    public static const MANAGER:int = 7;
    public static const SUPPORT:int = 8;
    public static const ADMIN:int = 9;

    public static const VALID_VALUES:Set = new Set(NORMAL, PREMIUM, MANAGER, SUPPORT, ADMIN);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[NORMAL] = "NORMAL";
      VALUES_TO_NAMES[PREMIUM] = "PREMIUM";
      VALUES_TO_NAMES[MANAGER] = "MANAGER";
      VALUES_TO_NAMES[SUPPORT] = "SUPPORT";
      VALUES_TO_NAMES[ADMIN] = "ADMIN";

    }
  }
}
