/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class SharedNotebookPrivilegeLevel   {
    public static const READ_NOTEBOOK:int = 0;
    public static const MODIFY_NOTEBOOK_PLUS_ACTIVITY:int = 1;
    public static const READ_NOTEBOOK_PLUS_ACTIVITY:int = 2;
    public static const GROUP:int = 3;
    public static const FULL_ACCESS:int = 4;
    public static const BUSINESS_FULL_ACCESS:int = 5;

    public static const VALID_VALUES:Set = new Set(READ_NOTEBOOK, MODIFY_NOTEBOOK_PLUS_ACTIVITY, READ_NOTEBOOK_PLUS_ACTIVITY, GROUP, FULL_ACCESS, BUSINESS_FULL_ACCESS);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[READ_NOTEBOOK] = "READ_NOTEBOOK";
      VALUES_TO_NAMES[MODIFY_NOTEBOOK_PLUS_ACTIVITY] = "MODIFY_NOTEBOOK_PLUS_ACTIVITY";
      VALUES_TO_NAMES[READ_NOTEBOOK_PLUS_ACTIVITY] = "READ_NOTEBOOK_PLUS_ACTIVITY";
      VALUES_TO_NAMES[GROUP] = "GROUP";
      VALUES_TO_NAMES[FULL_ACCESS] = "FULL_ACCESS";
      VALUES_TO_NAMES[BUSINESS_FULL_ACCESS] = "BUSINESS_FULL_ACCESS";

    }
  }
}
