/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.evernote.edam.type 
{
import org.apache.thrift.Set;
import flash.utils.Dictionary;
  public class SharedNotebookInstanceRestrictions   {
    public static const ONLY_JOINED_OR_PREVIEW:int = 1;
    public static const NO_SHARED_NOTEBOOKS:int = 2;

    public static const VALID_VALUES:Set = new Set(ONLY_JOINED_OR_PREVIEW, NO_SHARED_NOTEBOOKS);
    public static const VALUES_TO_NAMES:Dictionary = new Dictionary();
    {
      VALUES_TO_NAMES[ONLY_JOINED_OR_PREVIEW] = "ONLY_JOINED_OR_PREVIEW";
      VALUES_TO_NAMES[NO_SHARED_NOTEBOOKS] = "NO_SHARED_NOTEBOOKS";

    }
  }
}
